<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE ipfx [<!ELEMENT ipfx (queues,extensions)><!ELEMENT queues (queue*)><!ELEMENT queue (description,status,answercount,abandonedcount,othercount,gradeofservice,extensionsloggedin,queueingcount,longestqueuetime,maximumcallsqueued,maximumqueuetime,totalqueuetimeforansweredcalls,totaltalktime,warningcount,warningtime,alertcount,alerttime,agents)><!ELEMENT description                    (#PCDATA)><!ELEMENT status                         (#PCDATA)><!ELEMENT answercount                    (#PCDATA)><!ELEMENT abandonedcount                 (#PCDATA)><!ELEMENT othercount                     (#PCDATA)><!ELEMENT gradeofservice                 (#PCDATA)><!ELEMENT extensionsloggedin             (#PCDATA)><!ELEMENT queueingcount                  (#PCDATA)><!ELEMENT longestqueuetime               (#PCDATA)><!ELEMENT maximumcallsqueued             (#PCDATA)><!ELEMENT maximumqueuetime               (#PCDATA)><!ELEMENT totalqueuetimeforansweredcalls (#PCDATA)><!ELEMENT totaltalktime                  (#PCDATA)><!ELEMENT warningcount                   (#PCDATA)><!ELEMENT warningtime                    (#PCDATA)><!ELEMENT alertcount                     (#PCDATA)><!ELEMENT alerttime                      (#PCDATA)><!ELEMENT agents (agent*)><!ELEMENT agent (answered,averagetalktime)><!ELEMENT answered                       (#PCDATA)><!ELEMENT averagetalktime                (#PCDATA)><!ATTLIST queue                  id CDATA #REQUIRED                  lastupdate CDATA #REQUIRED><!ATTLIST agent id CDATA #REQUIRED><!ELEMENT extensions (extension*)><!ELEMENT extension (description,status,location,breakcode,returntime,inwrap,awayfromdesk)><!ELEMENT description                    (#PCDATA)><!ELEMENT status                         (#PCDATA)><!ELEMENT location                       (#PCDATA)><!ELEMENT breakcode                      (#PCDATA)><!ELEMENT returntime                     (#PCDATA)><!ELEMENT inwrap                         (#PCDATA)><!ELEMENT awayfromdesk                   (#PCDATA)><!ATTLIST extension id CDATA #REQUIRED>] ><ipfx><queues><queue id="66400" lastupdate="17/07/2018 13:53:43"><description>Admissions New Application</description><status>Open</status><answercount>17</answercount><abandonedcount>0</abandonedcount><othercount>1</othercount><gradeofservice>86%</gradeofservice><extensionsloggedin>8</extensionsloggedin><queueingcount>0</queueingcount><longestqueuetime>0</longestqueuetime><maximumcallsqueued>1</maximumcallsqueued><maximumqueuetime>147</maximumqueuetime><totalqueuetimeforansweredcalls>432</totalqueuetimeforansweredcalls><totaltalktime>3682</totaltalktime><warningcount>6</warningcount><warningtime>60</warningtime><alertcount>8</alertcount><alerttime>120</alerttime><agents></agents></queue></queues><extensions></extensions></ipfx>
